name: Release

on:
  push:
    tags:
      - 'v*'

env:
  ARTIFACT_NAME: strohalm-backend
  VERSION: ${{ github.ref_name }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v -ldflags="-s -w -X main.Version=${VERSION}" -trimpath -o $ARTIFACT_NAME ./src

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: $ARTIFACT_NAME
      
