name: Release

on:
  workflow_dispatch:
    inputs:
      version:
          description: 'Version to release'
          required: true
          default: ''
  push:
    tags:
      - 'v*'

env:
  ARTIFACT_NAME: strohalm-backend
  VERSION: ${{ github.event.inputs.version != '' && github.event.inputs.version || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v -ldflags="-s -w -X main.Version=$VERSION" -trimpath -o $ARTIFACT_NAME ./src

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.ARTIFACT_NAME }}
